apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: passos-magicos-pushgateway
  namespace: mle-system
  labels:
    release: kps
    app: passos-magicos
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - passos-magicos
  selector:
    matchLabels:
      app: passos-magicos
      component: pushgateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
